env: "local" # Окружение - local, dev или prod
http_server: # конфигурация нашего http-сервера
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
db:
  user: "ios"
  password: "111111"
  path: "url_shortner"